### ISSUE TITLE
Make database table

### ISSUE THREAD

**Issue by Rossco1991** [4GeeksAcademy/Wish-or-Junk-Final-Project#10]
Create database to allow for users, posts, comments, and images

**Comment by UsuallyAwakeGuy** [comment]
User, Post, Comment, and Image models have been created with relevant backrefs and serializations. This has been committed to the branch. 

Creating the reference tables for Likes, Favorites, and Dislikes in underway.

**Comment by UsuallyAwakeGuy** [comment]
Liked Posts, Disliked Posts, Apod Article, Favorite Article tables with backrefs have been added to the data structure and have been committed to the branch. Ready for merge.
