### ISSUE TITLE
API Route set up

### ISSUE THREAD

**Issue by Rossco1991** [4GeeksAcademy/Wish-or-Junk-Final-Project#33]
Set up API routes to interact with backend so Users can be created, Passwords can be set, Images can be stored, comments can be set and retrieved, Posts can be made and retrieved

**Comment by Rossco1991** [comment]
Profiles can be made and stored with relative information

**Comment by UsuallyAwakeGuy** [comment]
Initial routes for Comments and Posts have been committed.
