### ISSUE TITLE
Posts

### ISSUE THREAD

**Issue by Rossco1991** [4GeeksAcademy/Wish-or-Junk-Final-Project#6]
Create post and comment section so users can share their pictures and be able to comment on findings

**Comment by Rossco1991** [comment]
https://freefrontend.com/bootstrap-comments/

**Comment by Rossco1991** [comment]
Have posts pop up as modal

**Comment by Newux** [comment]
Created posts framework with component and page and separate style sheet, files were created in the profile branch
